spring:
  application:
    name: gateway-service
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        issuer-uri: http://keycloak:8080/realms/dh
  cloud:
    #config:
    #  discovery:
    #    serviceId: config-service
    #    enabled: true
    gateway:
      default-filters:
       # - TokenRelay=
        - AddRequestHeader=X-Gateway-Auth, requestFromGateway
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          #filters:
          #  - AddRequestHeader=X-Request-from, gateway
          #  - AddResponseHeader=X-Response-Red, Blue
          #  - StripPrefix=-1
        - id: users-swagger
          uri: lb://users-service
          predicates:
            - Path=/users/v3/api-docs, /users/swagger-ui/**, /users/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
        - id: auth-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs, /auth/swagger-ui/**, /auth/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          #uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: accounts-swagger
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/v3/api-docs, /accounts/swagger-ui/**, /accounts/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
server:
  port: 8081

#management:
#  tracing:
#    sampling:
#      probability: 1.0
eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka-service:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

#TOKENS
jwt:
  secret:
    key: nGit40Tx16L+KLDcd9Hc8/f9KxFT23XSNYXPtYN782DrqUsXGNBw5v4HTL4fkrcy8oEwPuyt13RKRUb4ILKSPP==